server:
  port: 9095

spring:
  application:
    name: query-service


  config:
    import: "classpath:variables.yml"

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ${db.username}
    password: ${db.password}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret-key: "BmoD/XUVKSxA5z2JNhrdiDl/1tF6N5QpLWPgVmO0RAE="
  issuer: "my-bank"
  expiry: 600000