server:
  port: 9094

spring:
  application:
    name: email-service


  mail:
    ##### SMTP configuration #####
    host: smtp.gmail.com
    port: 587
    username: asharkhan.eidiko@gmail.com
    password: ${APP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/